language: go
dist: trusty
sudo: required

before_install:
  - sudo apt-get install -y libsensors4
  - sudo apt-get install -y libsensors4-dev
  - go get github.com/modocache/gover
  - go get github.com/axnion/hrdwr
  - go get -t -v ./...
script:
  - go vet github.com/axnion/hrdwr
  - go test -v ./...
  - chmod -x test.sh
  - sudo ./test.sh
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email: false