language: go
dist: trusty
sudo: required

before_install:
  - sudo apt-get install -y lm-sensors
  - go get github.com/modocache/gover
  - go get github.com/axnion/hrdwr
script:
  - go vet github.com/axnion/hrdwr
  - go test -v ./...
  - go test -race -coverprofile=coverage.txt -covermode=atomic
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email: false