coverage:
  precision: 2
  round: down
  range: 70...100

  status:
    # Learn more at https://codecov.io/docs#yaml_default_commit_status
    project: true
    patch: false
    changes: false
comment:
  layout: "header, diff"
  behavior: default  # update if exists else create new